default_platform(:ios)

platform :ios do
  desc "Unit tests"
  lane :test do
    scan(workspace: "gitRepoStars.xcworkspace", device: "iPhone 11 Pro", scheme: "gitRepoStars", code_coverage: true)
  
coverage_files_to_ignore = [
    'Sources/Resources/*',
    'Pods/*',
]

  slather(
      output_directory: "fastlane/html",
      workspace: "gitRepoStars.xcworkspace",
      html: true,
      scheme: "gitRepoStars",
      proj: "gitRepoStars.xcodeproj",
      ignore: coverage_files_to_ignore,
      verbose: true,
      show: true
  )
  end
end